@Server_HostAddress = https://localhost:7024

# Get OpenApi specification
GET {{Server_HostAddress}}/openapi/v1.json
Accept: application/json
###

# 1. Start a chat - Returns the id of the chat for subsequent requests

# @name chat
POST {{Server_HostAddress}}/chat
Accept: */*
Content-Type: application/json 
{
  "message": "What happened between the reigns of Charles I and Charles II in Great Britain?"
}
###

# 2. Get Last Response - If awaiting response will return 'Still thinking...'
GET {{Server_HostAddress}}/chat/{{chat.response.body.$.id}}
Accept: */*
Content-Type: application/json 
###

# 3. Get Conversation - If awaiting response, last entry will return 'Still thinking...'
GET {{Server_HostAddress}}/chat/conversation/{{chat.response.body.$.id}}
Accept: */*
Content-Type: application/json 
###

# 4. Chat with continuation
POST {{Server_HostAddress}}/chat/{{chat.response.body.$.id}}
Accept: */*
Content-Type: application/json 
{
  "message": "Summarise in less than 50 words"
}
###

# 5. Chat with continuation
POST {{Server_HostAddress}}/chat/{{chat.response.body.$.id}}
Accept: */*
Content-Type: application/json 
{
  "message": "And in Spanish"
}
###

# 5. Chat with continuation
POST {{Server_HostAddress}}/chat/{{chat.response.body.$.id}}
Accept: */*
Content-Type: application/json 
{
  "message": "With a pirate accent"
}
###

# 6. Clear specified chat
GET {{Server_HostAddress}}/chat/clear/{{chat.response.body.$.id}}
Accept: */*
Content-Type: application/json 
###

# Sample request to get weather information scaffolded on project creation
GET {{Server_HostAddress}}/weather/
Accept: application/json
###